Feature/crear calificacion auditar
qbits-mx/tienda-backend pull request #146
Opened 2022-01-24 15:22 UTC by crispin79

En esta rama se encuentran los microservicios de Auditar comentario para un administrador y Historial de compras de un anuncio

2022-01-24 22:43 UTC, arellano-gustavo commented
ESTA RAMA NI SIQUIERA COMPILA !!!!!!!!

<img width="520" alt="imagen" src="https://user-images.githubusercontent.com/17259655/150877320-52110c77-bbe4-4cdc-9a3b-b1e1b51c20a9.png">

2022-01-24 22:51 UTC, arellano-gustavo requested changes
ESTA RAMA NI SIQUIERA COMPILA

2022-01-24 22:51 UTC, arellano-gustavo commented on src/main/java/mx/qbits/tienda/api/mapper/RegistroMapper.java
> -/*
PORQUÉ BORRARON VARIOS MAPPERS ???
ESO HACE QUE ESTE PROYECTO NI SIQUIERA COMPILE !!!!!!

2022-01-25 01:42 UTC, JoseRamirezRojas commented
Hemos corregido los errores, nos puedes revisar otra vez ?

2022-01-26 12:06 UTC, merged